apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ascii-live-tls-prod-cert
  namespace: ascii-live
spec:
  secretName: ascii-live-tls-prod-cert
  dnsNames:
  - ascii.live
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ascii.live
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

