apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ascii-live
  namespace: ascii-live
spec:
  template:
    metadata:
      labels:
        app: ascii-live
    spec:
      containers:
      - image: hugomd/ascii-live:8d6157e3
        name: ascii-live
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ascii-live
  namespace: ascii-live
spec:
  selector:
    app: ascii-live
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ascii-live
  namespace: ascii-live
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/preserve-host: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: ascii.live
    http:
      paths:
      - path: /
        backend:
          serviceName: ascii-live
          servicePort: 8080
  tls:
    - secretName: ascii-live-tls-prod-cert
      hosts:
        - ascii.live
